name: Deploy Changes

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notify server over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.SERVER_HOST }}
          port: ${{ vars.SERVER_PORT }}
          username: ${{ vars.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          request_pty: false
